export const animeList = [
  { id: 1, name: "Naruto", image: "/images/animes/naruto.jpg" },
  { id: 2, name: "One Piece", image: "/images/animes/one_piece.jpg" },
  { id: 3, name: "Dragon Ball Z", image: "/images/animes/dbz.png" },
  { id: 4, name: "Attack on Titan", image: "/images/animes/snk.png" },
  { id: 5, name: "Demon Slayer", image: "/images/animes/demon_slayer.jpg" },
  { id: 6, name: "My Hero Academia", image: "/images/animes/my_hero_academia.jpg" },
  { id: 7, name: "Fullmetal Alchemist", image: "/images/animes/full_metal.jpg" },
  { id: 8, name: "Tokyo Ghoul", image: "/images/animes/tokyo_ghoul.jpg" },
  { id: 9, name: "Bleach", image: "/images/animes/bleach.png" },
  { id: 10, name: "One Punch Man", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21087-B5DHjqZ3kW4b.jpg" },
  { id: 11, name: "Death Note", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-kUgkcrfOrkUM.jpg" },
  { id: 12, name: "Sword Art Online", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11757-SxYDUzdr9rh2.jpg" },
  { id: 13, name: "Cowboy Bebop", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1-GCsPm7waJ4kS.png" },
  { id: 14, name: "Neon Genesis Evangelion", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx30-AI1zr74Dh4ye.jpg" },
  { id: 15, name: "Fairy Tail", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx12049-FIx0K2s81SPa.png" },
  { id: 16, name: "Hunter x Hunter", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx13271-jBxQFqHCpb2K.png" },
  { id: 17, name: "Black Clover", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx131680-gjs8mMQPmkOQ.png" },
  { id: 18, name: "Meitantei Conan", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx156841-eCdzTqfaqNb7.png" },
  { id: 19, name: "Tokyo Revengers", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142853-nxEZDE9oDRLG.png" },
  { id: 20, name: "JoJo's Bizarre Adventure", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20799-S1eyqBDlx51E.jpg" },
  { id: 21, name: "Vinland Saga", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101348-2fhDFPCuMNiz.jpg" },
  { id: 22, name: "Erased", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21234-XmqW39aQ9o7O.jpg" },
  { id: 23, name: "Jujutsu Kaisen", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-LHBAeoZDIsnF.jpg" },
  { id: 24, name: "Black Butler", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx6793-WJHPwa0ofanb.png" },
  { id: 25, name: "The Promised Neverland", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101759-8UR7r9MNVpz2.jpg" },
  { id: 26, name: "Berserk", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21560-6iifjdssfebJ.jpg" },
  { id: 27, name: "Solo Leveling", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png" },
  { id: 28, name: "Baki", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx97888-tdZ1r7qN1DRs.jpg" },
  { id: 29, name: "Dr.Stone", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142876-izO35hPP2DZ9.jpg" },
  { id: 30, name: "Blue Lock", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx137822-U8naszP96vzC.png" },
  { id: 31, name: "Saint Seiya", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1254.jpg" },
  { id: 32, name: "Parasyte", image: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20623-dUARfggnNDOe.jpg" },
];
