export const videoGamesList = [
  { id: 1, name: "PlayStation 5", image: "" },
  { id: 2, name: "Nintendo 64", image: "" },
  { id: 3, name: "Dreamcast", image: "" },
  { id: 4, name: "Xbox Series X", image: "" },
  { id: 5, name: "PlayStation 2", image: "" },
  { id: 6, name: "Game Boy Advance", image: "" },
  { id: 7, name: "Atari 2600", image: "" },
  { id: 8, name: "Nintendo Switch", image: "" },
  { id: 9, name: "PlayStation 3", image: "" },
  { id: 10, name: "GameCube", image: "" },
  { id: 11, name: "Xbox 360", image: "" },
  { id: 12, name: "Sega Saturn", image: "" },
  { id: 13, name: "Super Nintendo (SNES)", image: "" },
  { id: 14, name: "PlayStation 4", image: "" },
  { id: 15, name: "Wii", image: "" },
  { id: 16, name: "Neo Geo", image: "" },
  { id: 17, name: "Xbox One", image: "" },
  { id: 18, name: "PlayStation 1", image: "" },
  { id: 19, name: "Game Boy Color", image: "" },
  { id: 20, name: "Mega Drive / Genesis", image: "" },
  { id: 21, name: "Nintendo DS", image: "" },
  { id: 22, name: "PSP", image: "" },
  { id: 23, name: "Wii U", image: "" },
  { id: 24, name: "Sega Master System", image: "" },
  { id: 25, name: "Nintendo 3DS", image: "" },
  { id: 26, name: "PlayStation Vita", image: "" },
  { id: 27, name: "ColecoVision", image: "" },
  { id: 28, name: "Xbox", image: "" },
  { id: 29, name: "Nintendo Entertainment System (NES)", image: "" },
  { id: 30, name: "Steam Deck", image: "" },
  { id: 31, name: "TurboGrafx-16 / PC Engine", image: "" },
  { id: 32, name: "Nintendo Switch OLED", image: "" },
];
