export const esportList = [
  { id: 1, name: "Fnatic", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f4/Fnatic-Logo-2020.svg/1200px-Fnatic-Logo-2020.svg.png" },
  { id: 2, name: "Team Liquid", image: "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/9/9a/Team_Liquidlogo_square_Dark.png" },
  { id: 3, name: "Karmine", image: "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/2/2d/Karmine_Corplogo_square.png" },
  { id: 4, name: "G2 Esports", image: "https://upload.wikimedia.org/wikipedia/fr/e/e4/G2_Esports.svg" },
  { id: 5, name: "Navi", image: "https://upload.wikimedia.org/wikipedia/fr/2/27/NAVI_Logo_2020.png" },
  { id: 6, name: "Evil Geniuses", image: "https://www.thespike.gg/_next/image?url=https%3A%2F%2Fcdn.thespike.gg%2Fweasel%252F285px-Evil_Geniuses_2024_darkmode_1741958947603.png&w=640&q=75" },
  { id: 7, name: "T1", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f9/T1_logo.svg/300px-T1_logo.svg.png?20220705132346" },
  { id: 8, name: "FaZe Clan", image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Faze_Clan.svg" },
  { id: 9, name: "Ninjas in Pyjamas", image: "https://upload.wikimedia.org/wikipedia/fr/7/7e/NIP-Symbol-RGB-Neon_Yellow.svg" },
  { id: 10, name: "Vitality", image: "https://upload.wikimedia.org/wikipedia/fr/3/30/Team_Vitality_Logo_2018.png" },
  { id: 11, name: "100 Thieves", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/100_Thieves_logo.svg/1280px-100_Thieves_logo.svg.png" },
  { id: 12, name: "MAD Lions", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/8/84/MAD_Lions_logo.svg/640px-MAD_Lions_logo.svg.png" },
  { id: 13, name: "Team Secret", image: "https://upload.wikimedia.org/wikipedia/en/2/2a/Team_Secret_logo.svg" },
  { id: 14, name: "Falcons", image: "https://static.wikia.nocookie.net/fortnite_esports_gamepedia_en/images/5/58/Falcons_Esportlogo_square.png" },
  { id: 15, name: "Astralis", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Astralis.svg/800px-Astralis.svg.png" },
  { id: 16, name: "SK Gaming", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/SK_Gaming_Logo_2022.svg/768px-SK_Gaming_Logo_2022.svg.png" },
  { id: 17, name: "NRG", image: "https://storage.ensigame.com/logos/teams/1c9656e2541401b7a1aa5c0c0d3aa88e.png" },
  { id: 18, name: "GiantX", image: "https://upload.wikimedia.org/wikipedia/en/0/0e/GiantX_logo.svg" },
  { id: 19, name: "M8", image: "https://upload.wikimedia.org/wikipedia/commons/b/be/Gentle_Mates_2025.png" },
  { id: 20, name: "Dignitas", image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Dignitas_logo.svg/1200px-Dignitas_logo.svg.png" },
  { id: 21, name: "Furia", image: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/FURIA_Esports_logo.svg/1200px-FURIA_Esports_logo.svg.png" },
  { id: 22, name: "Gen.G", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Gen.G_Logo.svg/1200px-Gen.G_Logo.svg.png" },
  { id: 23, name: "DRX", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/DRX_logo_2023.png/960px-DRX_logo_2023.png" },
  { id: 24, name: "Rogue", image: "https://upload.wikimedia.org/wikipedia/en/a/af/Rogue_logo.svg" },
  { id: 25, name: "The Ultimates", image: "https://storage.ensigame.com/logos/teams/1ee23dc2a44c20ae6ba20e39c0d08b34.png" },
  { id: 26, name: "KT Rolster", image: "https://upload.wikimedia.org/wikipedia/en/6/61/KT_Rolster_logo.png" },
  { id: 27, name: "Geekay", image: "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f6/Geekay_Esportslogo_square.png" },
  { id: 28, name: "BDS", image: "https://maxesport.gg/medias/2022/01/Logo-BDS.webp" },
  { id: 29, name: "Team Heretics", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/6/69/Team_Heretics.png/1200px-Team_Heretics.png" },
  { id: 30, name: "ENCE", image: "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5e/ENCE.svg/1200px-ENCE.svg.png" },
  { id: 31, name: "Cloud9", image: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Cloud9.png" },
  { id: 32, name: "Heroic", image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Heroic_2023_logo.png" },
];
