const basePath = import.meta.env.BASE_URL;

export const heroesList = [
  { id: 1, name: "Iron Man", image: `${basePath}images/heroes/iron_man.jpg` },
  { id: 2, name: "Wonder Woman", image: `${basePath}images/heroes/wonder_woman.webp`,
  winnerName: "W_Woman" },
  { id: 3, name: "Captain America", image: `${basePath}images/heroes/captain_america.webp`,
  winnerName: "C_America" },
  { id: 4, name: "Black Panther", image: `${basePath}images/heroes/black_panther.webp`,
  winnerName: "B_Panther" },
  { id: 5, name: "The Flash", image: `${basePath}images/heroes/the_flash.jpg`,
  winnerName: "Flash" },
  { id: 6, name: "Thor", image: `${basePath}images/heroes/thor.jpg` },
  { id: 7, name: "Hulk", image: `${basePath}images/heroes/hulk.jpg` },
  { id: 8, name: "Doctor Strange", image: `${basePath}images/heroes/dr_strange.jpg`,
  winnerName: "DrStrange" },
  { id: 9, name: "Scarlet Witch", image: `${basePath}images/heroes/scarlet_witch.webp`,
  winnerName: "Scarlet" },
  { id: 10, name: "Wolverine", image: `${basePath}images/heroes/wolverine.webp` },
  { id: 11, name: "Deadpool", image: `${basePath}images/heroes/deadpool.png` },
  { id: 12, name: "Green Lantern", image: `${basePath}images/heroes/green_lantern.jpg`,
  winnerName: "G_Lantern" },
  { id: 13, name: "Aquaman", image: `${basePath}images/heroes/aquaman.webp` },
  { id: 14, name: "Superman", image: `${basePath}images/heroes/superman.jpg` },
  { id: 15, name: "Cyborg", image: `${basePath}images/heroes/cyborg.webp` },
  { id: 16, name: "Star-Lord", image: `${basePath}images/heroes/star_lord.jpg`,
  winnerName: "StarLord" },
  { id: 17, name: "Gamora", image: `${basePath}images/heroes/gamora.webp` },
  { id: 18, name: "Rocket Raccoon", image: `${basePath}images/heroes/rocket_racoon.jpg`,
  winnerName: "Raccoon" },
  { id: 19, name: "Daredevil", image: `${basePath}images/heroes/daredevil.jpg` },
  { id: 20, name: "Silver Surfer", image: `${basePath}images/heroes/silver_surfer.jpg`,
  winnerName: "S_Surfer" },
  { id: 21, name: "Vision", image: `${basePath}images/heroes/vision.jpg` },
  { id: 22, name: "Ant-Man", image: `${basePath}images/heroes/ant_man.jpg` },
  { id: 23, name: "Storm", image: `${basePath}images/heroes/storm.jpeg` },
  { id: 24, name: "Batman", image: `${basePath}images/heroes/batman.png` },
  { id: 25, name: "Rogue", image: `${basePath}images/heroes/rogue.jpg` },
  { id: 26, name: "Beast", image: `${basePath}images/heroes/beast.jpg` },
  { id: 27, name: "Black Widow", image: `${basePath}images/heroes/black_widow.webp`,
  winnerName: "B_Widow" },
  { id: 28, name: "Spider-Man", image: `${basePath}images/heroes/spiderman.png`,
  winnerName: "SpiderMan" },
  { id: 29, name: "Green Arrow", image: `${basePath}images/heroes/green_arrow.webp`,
  winnerName: "G_Arrow" },
  { id: 30, name: "Shazam", image: `${basePath}images/heroes/shazam.png` },
  { id: 31, name: "Hawkeye", image: `${basePath}images/heroes/hawkeye.webp` },
  { id: 32, name: "Hawkgirl", image: `${basePath}images/heroes/hawkgirl.webp` },
];
