const basePath = import.meta.env.BASE_URL;

export const heroesList = [
  { id: 1, name: "Iron Man", image: `${basePath}images/heroes/iron_man.jpg` },
  { id: 2, name: "Wonder Woman", image: `${basePath}images/heroes/wonder_woman.webp`,
  winnerName: "W_Woman" },
  { id: 3, name: "Captain America", image: `${basePath}images/heroes/captain_america.webp`,
  winnerName: "C_America" },
  { id: 4, name: "Black Panther", image: `${basePath}images/heroes/black_panther.webp`,
  winnerName: "B_Panther" },
  { id: 5, name: "The Flash", image: `${basePath}images/heroes/the_flash.jpg`,
  winnerName: "Flash" },
  { id: 6, name: "Thor", image: "https://static0.srcdn.com/wordpress/wp-content/uploads/2025/05/chris-hemsworth-s-thor-looks-up-while-carrying-surtur-s-crown-in-thor-ragnarok.jpg?w=1600&h=900&fit=crop" },
  { id: 7, name: "Hulk", image: `${basePath}images/heroes/hulk.jpg` },
  { id: 8, name: "Doctor Strange", image: "https://www.marvel-cineverse.fr/medias/images/doctorstrange-dsmom-imgprofil-1.jpg",
  winnerName: "Strange" },
  { id: 9, name: "Scarlet Witch", image: `${basePath}images/heroes/scarlet_witch.webp`,
  winnerName: "Scarlet" },
  { id: 10, name: "Wolverine", image: `${basePath}images/heroes/wolverine.webp` },
  { id: 11, name: "Deadpool", image: `${basePath}images/heroes/deadpool.webp` },
  { id: 12, name: "Green Lantern", image: `${basePath}images/heroes/green_lantern.jpg`,
  winnerName: "G_Lantern" },
  { id: 13, name: "Aquaman", image: `${basePath}images/heroes/aquaman.webp` },
  { id: 14, name: "Superman", image: `${basePath}images/heroes/superman.jpg` },
  { id: 15, name: "Cyborg", image: `${basePath}images/heroes/cyborg.webp` },
  { id: 16, name: "Star-Lord", image: `${basePath}images/heroes/star_lord.jpg`,
  winnerName: "StarLord" },
  { id: 17, name: "Gamora", image: `${basePath}images/heroes/gamora.webp` },
  { id: 18, name: "Rocket Raccoon", image: `${basePath}images/heroes/rocket_racoon.jpg`,
  winnerName: "Raccoon" },
  { id: 19, name: "Daredevil", image: `${basePath}images/heroes/daredevil.jpg` },
  { id: 20, name: "Silver Surfer", image: "https://cdn.britannica.com/16/182816-050-21F98A9B/Fantastic-Four-Rise-of-the-Silver-Surfer.jpg",
  winnerName: "S_Surfer" },
  { id: 21, name: "Vision", image: `${basePath}images/heroes/vision.jpg` },
  { id: 22, name: "Ant-Man", image: "https://dlrp.fr/wp-content/uploads/2019/07/757646178808.jpeg" },
  { id: 23, name: "Storm", image: "https://i.namu.wiki/i/7Tj6RfvFiqlQ1tO0HHYpf8KctHhSeA-Aeqd2nIp5WvX3bqq-gc8A62YxgE38r_aZxcP4CySk8Ui57wniSnRIsQ.webp" },
  { id: 24, name: "Batman", image: `${basePath}images/heroes/batman.png` },
  { id: 25, name: "Rogue", image: `${basePath}images/heroes/rogue.jpg` },
  { id: 26, name: "Beast", image: `${basePath}images/heroes/beast.jpg` },
  { id: 27, name: "Black Widow", image: "https://www.nme.com/wp-content/uploads/2018/02/Black-Widow-Avengers.jpg",
  winnerName: "B_Widow" },
  { id: 28, name: "Spider-Man", image: `${basePath}images/heroes/spiderman.png`,
  winnerName: "SpiderMan" },
  { id: 29, name: "Green Arrow", image: `${basePath}images/heroes/green_arrow.webp`,
  winnerName: "G_Arrow" },
  { id: 30, name: "Shazam", image: `${basePath}images/heroes/shazam.webp` },
  { id: 31, name: "Hawkeye", image: `${basePath}images/heroes/hawkeye.webp` },
  { id: 32, name: "Hawkgirl", image: `${basePath}images/heroes/hawkgirl.webp` },
];
