export const onepieceList = [
  { id: 1, name: "Kaido", image: "https://static.wikia.nocookie.net/onepiece/images/2/28/Kaidou_Wanted_Poster.png" },
  { id: 2, name: "Roronoa Zoro", image: "https://static.wikia.nocookie.net/onepiece/images/a/a6/Zoro%27s_Wanted_Poster.png" },
  { id: 3, name: "Nami", image: "https://static.wikia.nocookie.net/onepiece/images/4/48/Nami%27s_Wanted_Poster.png" },
  { id: 4, name: "Sanji", image: "https://static.wikia.nocookie.net/onepiece/images/d/db/Sanji%27s_Wanted_Poster.png" },
  { id: 5, name: "Nico Robin", image: "https://static.wikia.nocookie.net/onepiece/images/5/55/Nico_Robin%27s_Wanted_Poster.png" },
  { id: 6, name: "Portgas D. Ace", image: "https://static.wikia.nocookie.net/onepiece/images/b/bd/Portgas_D._Ace%27s_Wanted_Poster.png" },
  { id: 7, name: "Trafalgar D. Water Law", image: "https://static.wikia.nocookie.net/onepiece/images/d/d4/Law%27s_Wanted_Poster.png" },
  { id: 8, name: "Boa Hancock", image: "" },
  { id: 9, name: "Shanks le Roux", image: "https://static.wikia.nocookie.net/onepiece/images/0/0b/Shanks_Wanted_Poster.png" },
  { id: 10, name: "Brook", image: "https://static.wikia.nocookie.net/onepiece/images/5/5a/Brook_Alive_Bounty_Poster.png" },
  { id: 11, name: "Franky", image: "https://static.wikia.nocookie.net/onepiece/images/1/1d/Franky%27s_Wanted_Poster.png" },
  { id: 12, name: "Tony-Tony Chopper", image: "https://static.wikia.nocookie.net/onepiece/images/3/3e/Tony_Tony_Chopper%27s_Wanted_Poster.png" },
  { id: 13, name: "Jinbe", image: "https://static.wikia.nocookie.net/onepiece/images/7/71/Jinbe%27s_Current_Wanted_Poster.png" },
  { id: 14, name: "Dracule Mihawk", image: "https://static.wikia.nocookie.net/onepiece/images/4/46/Mihawk%27s_Wanted_Poster.png" },
  { id: 15, name: "Sabo", image: "https://static.wikia.nocookie.net/onepiece/images/4/49/Sabo%27s_Wanted_Poster.png" },
  { id: 16, name: "Donquixote Doflamingo", image: "" },
  { id: 17, name: "Eustass Kid", image: "https://static.wikia.nocookie.net/onepiece/images/9/96/Eustass_Kid%27s_Third_Wanter_Poster.png" },
  { id: 18, name: "Monkey D. Luffy", image: "https://static.wikia.nocookie.net/onepiece/images/6/62/Luffy_Wanted_Poster.png" },
  { id: 19, name: "Big Mom", image: "https://static.wikia.nocookie.net/onepiece/images/a/ae/Charlotte_Linlin_Wanted_Poster.png" },
  { id: 20, name: "Gol D. Roger", image: "https://static.wikia.nocookie.net/onepiece/images/9/90/Gol_D._Roger_Wanted_Poster.png" },
  { id: 21, name: "Edward Newgate", image: "https://static.wikia.nocookie.net/onepiece/images/8/8e/Edward_Newgate_Wanted_Poster.png" },
  { id: 22, name: "Koby", image: "" },
  { id: 23, name: "Smoker", image: "" },
  { id: 24, name: "Charlotte Katakuri", image: "" },
  { id: 25, name: "Vinsmoke Reiju", image: "" },
  { id: 26, name: "Enel", image: "" },
  { id: 27, name: "Crocodile", image: "https://static.wikia.nocookie.net/onepiece/images/1/14/Crocodile%27s_Wanted_Poster.png" },
  { id: 28, name: "Rob Lucci", image: "" },
  { id: 29, name: "Monkey D. Garp", image: "https://static.wikia.nocookie.net/onepiece/images/e/e1/Monkey_D._Garp_Anime_Infobox.png" },
  { id: 30, name: "Bellamy", image: "" },
  { id: 31, name: "Foxy", image: "" },
  { id: 32, name: "Perona", image: "" },
];
