export const seriesList = [
  { id: 1, name: "Chernobyl", image: "https://a.ltrbxd.com/resized/film-poster/5/3/2/0/8/2/532082-chernobyl-0-1000-0-1500-crop.jpg?v=ff1851eaee" },
  { id: 2, name: "Stranger Things", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg" },
  { id: 3, name: "The Office", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg" },
  { id: 4, name: "The Walking Dead", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/ng3cMtxYKt1OSQYqFlnKWnVsqNO.jpg" },
  { id: 5, name: "Alice in Borderland", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/Ac8ruycRXzgcsndTZFK6ouGA0FA.jpg",
  winnerName: "Alice in B_" },
  { id: 6, name: "Young Sheldon", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/kidkbZRBGbsEIrX7pODRSKi9ipl.jpg" },
  { id: 7, name: "Malcolm in the Middle", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/ckLLIsNy3Z0Go1PYHA2PHzVymUA.jpg",
  winnerName: "Malcolm" },
  { id: 8, name: "Friends", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg" },
  { id: 9, name: "Suits", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/vQiryp6LioFxQThywxbC6TuoDjy.jpg" },
  { id: 10, name: "The Sopranos", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg" },
  { id: 11, name: "Prison Break", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/z885tJn5kkUHppjIK1g2Q54iTff.jpg" },
  { id: 12, name: "Supernatural", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg" },
  { id: 13, name: "Grey's Anatomy", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/hjJkrLXhWvGHpLeLBDFznpBTY1S.jpg" },
  { id: 14, name: "Desperate Housewives", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/4qeI51jDzH81PpUUNaJCBrfm7f6.jpg",
  winnerName: "D_Housewives" },
  { id: 15, name: "Breaking Bad", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg" },
  { id: 16, name: "Charmed", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/z4bPJ1BWU2EtV69NII2GVvsugQ2.jpg" },
  { id: 17, name: "How to Get Away with Murder", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/bJs8Y6T88NcgksxA8UaVl4YX8p8.jpg",
  winnerName: "...Murder" },
  { id: 18, name: "How I met your Mother", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg",
  winnerName: "...Mother" },
  { id: 19, name: "Peaky Blinders", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg" },
  { id: 20, name: "The Blacklist", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/4HTfd1PhgFUenJxVuBDNdLmdr0c.jpg" },
  { id: 21, name: "Dark", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg" },
  { id: 22, name: "Squid Game", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg" },
  { id: 23, name: "The 100", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg" },
  { id: 24, name: "Criminal Minds", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/7igSTed2htAIEXAMuUJSrk05ERV.jpg" },
  { id: 25, name: "Black Mirror", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg" },
  { id: 26, name: "The Boys", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg" },
  { id: 27, name: "One Tree Hill", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/sOrelBaAhp7DZbPTivDwKEyPslC.jpg" },
  { id: 28, name: "Better Call Saul", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg" },
  { id: 29, name: "Narcos", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/rTmal9fDbwh5F0waol2hq35U4ah.jpg" },
  { id: 30, name: "Snowfall", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/y7ntzl7msiaS6o7dvDbNG7XFYcR.jpg" },
  { id: 31, name: "Lost", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg" },
  { id: 32, name: "Game of Thrones", image: "https://serializd-tmdb-images.b-cdn.net/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg" },
];
