export const yugiohList = [
  { id: 1, name: "Dark Magician", image: "https://images.ygoprodeck.com/images/cards/46986414.jpg" },
  { id: 2, name: "Blue-Eyes White Dragon", image: "https://images.ygoprodeck.com/images/cards/89631139.jpg" },
  { id: 3, name: "Red-Eyes Black Dragon", image: "https://images.ygoprodeck.com/images/cards/74677422.jpg" },
  { id: 4, name: "Summoned Skull", image: "https://images.ygoprodeck.com/images/cards/70781052.jpg" },
  { id: 5, name: "Celtic Guardian", image: "https://images.ygoprodeck.com/images/cards/91152256.jpg" },
  { id: 6, name: "Kuriboh", image: "https://images.ygoprodeck.com/images/cards/40640057.jpg" },
  { id: 7, name: "Dark Magician Girl", image: "https://images.ygoprodeck.com/images/cards/38033121.jpg" },
  { id: 8, name: "Time Wizard", image: "https://images.ygoprodeck.com/images/cards/71625222.jpg" },
  { id: 9, name: "Jinzo", image: "https://images.ygoprodeck.com/images/cards/77585513.jpg" },
  { id: 10, name: "Exodia the Forbidden One", image: "https://images.ygoprodeck.com/images/cards/33396948.jpg" },
  { id: 11, name: "Buster Blader", image: "https://images.ygoprodeck.com/images/cards/78193831.jpg" },
  { id: 12, name: "Relinquished", image: "https://images.ygoprodeck.com/images/cards/64631466.jpg" },
  { id: 13, name: "Black Luster Soldier", image: "https://images.ygoprodeck.com/images/cards/5405694.jpg" },
  { id: 14, name: "Dark Necrofear", image: "https://images.ygoprodeck.com/images/cards/31829185.jpg" },
  { id: 15, name: "Barrel Dragon", image: "https://images.ygoprodeck.com/images/cards/81480460.jpg" },
  { id: 16, name: "Harpie Lady", image: "https://images.ygoprodeck.com/images/cards/76812113.jpg" },
  { id: 17, name: "Cyber Dragon", image: "https://images.ygoprodeck.com/images/cards/70095154.jpg" },
  { id: 18, name: "Elemental HERO Neos", image: "https://images.ygoprodeck.com/images/cards/89943723.jpg" },
  { id: 19, name: "Winged Kuriboh", image: "https://images.ygoprodeck.com/images/cards/57116033.jpg" },
  { id: 20, name: "The Winged Dragon of Ra", image: "https://images.ygoprodeck.com/images/cards/10000020.jpg" },
  { id: 21, name: "Obelisk the Tormentor", image: "https://images.ygoprodeck.com/images/cards/10000000.jpg" },
  { id: 22, name: "Slifer the Sky Dragon", image: "https://images.ygoprodeck.com/images/cards/10000010.jpg" },
  { id: 23, name: "Magician of Black Chaos", image: "https://images.ygoprodeck.com/images/cards/30208479.jpg" },
  { id: 24, name: "Skull Servant", image: "https://images.ygoprodeck.com/images/cards/32274490.jpg" },
  { id: 25, name: "Great Maju Garzett", image: "https://images.ygoprodeck.com/images/cards/55623480.jpg" },
  { id: 26, name: "Dark Ruler Ha Des", image: "https://images.ygoprodeck.com/images/cards/70781052.jpg" },
  { id: 27, name: "Luster Dragon", image: "https://images.ygoprodeck.com/images/cards/11091375.jpg" },
  { id: 28, name: "Penguin Soldier", image: "https://images.ygoprodeck.com/images/cards/93920745.jpg" },
  { id: 29, name: "Toon Summoned Skull", image: "https://images.ygoprodeck.com/images/cards/91842653.jpg" },
  { id: 30, name: "Toon Mermaid", image: "https://images.ygoprodeck.com/images/cards/65458948.jpg" },
  { id: 31, name: "Trap Master", image: "https://images.ygoprodeck.com/images/cards/46461247.jpg" },
  { id: 32, name: "La Jinn the Mystical Genie", image: "https://images.ygoprodeck.com/images/cards/97590747.jpg" },
];
